### ISSUE TITLE
eeprom scripts cannot write > 255 bytes

### ISSUE THREAD

**Issue by nsdrude** [varjig/var_kit_test#4]
See: https://github.com/varjig/var_kit_test/blob/master/am62_vareeprom_dram.sh#L13-L34

For EEPROM offsets > 255, the address must be incremented. For example:

```
I2C Addr: 0x50, Memory: 0x000 to 0x0ff
I2C Addr: 0x51, Memory: 0x1ff to 0x1ff
etc...
```
For example, write `0xabab` to address `0x1a0` in AM62 U-Boot an read it in Linux:
```
Write a test byte in U-Boot
u-boot> i2c dev 3; I2C_BUS=0x3; I2C_DEV=0x50; I2C_HEADER_OFFSET=0x0;
u-boot> mw.w $loadaddr 0xabab 1
u-boot> eeprom write $I2C_BUS $I2C_DEV $loadaddr 0x1a0 2;

Read it in U-Boot
u-boot> eeprom read $I2C_BUS $I2C_DEV 0x82000800 0 0x1ff
u-boot> md.b 0x82000800 0x1ff

Read it in Linux:
# i2cget -f -y 0x3 0x51 0xa0
```
We need to update the write_i2c_byte to account for this.

@ksloat thanks for discovering this
@eranmati  @varigigi FYI

**Comment by ksloat** [comment]
See the PR here:
https://github.com/varjig/var_kit_test/pull/5

**Comment by eranmati** [comment]
@ksloat @nsdrude, does this issue affect any of the current SOMs?

**Comment by ksloat** [comment]
@eranmati this would effect the 8, 93 and 62 only if they attempt to program an EEPROM image greater than 256 bytes. The new 1 GB configuration for the 93 exceeds this, and according to @nsdrude several of the 62 images do as well. I am not sure about the current EEPROM images of the 8.

In the current script, the behavior is that the EEPROM image will be written up to offset 255, and then the script will stop with an error in the i2cset command.

**Comment by eranmati** [comment]
Are there any images greater than 256 bytes that are being used right now in production with this script?
Do any of the jig script have the same issue?

**Comment by ksloat** [comment]
All of the files currently in the ddr folder of this repository are < 256 bytes. However, for the DART8 files, it seems that no script references these, and some other files are used instead that are not in this repository:
i.e.
```
1)
	EEPROM_IMAGE=VAR-SOM-MX8M-MINI-Samsung-2G-K4A8G165WC-BCTD.bin
	;;
2)
	EEPROM_IMAGE=VAR-SOM-MX8M-NANO-Samsung-1G-K4A8G165WC-BCTD.bin
	;;
3)
	EEPROM_IMAGE=VAR-SOM-MX8M-MINI-Samsung-2G-K4A8G165WC-BITD.bin
	;;
4)
	EEPROM_IMAGE=VAR-SOM-MX8M-NANO-Samsung-1G-K4A8G165WC-BITD.bin
	;;
5)
	EEPROM_IMAGE=VAR-SOM-MX8M-MINI-Samsung-4G-K4AAG165WA-BCTD.bin
	;;
6)
	EEPROM_IMAGE=VAR-SOM-MX8M-NANO-Samsung-2G-K4AAG165WA-BCTD.bin
	;;
7)
	EEPROM_IMAGE=VAR-SOM-MX8M-MINI-Samsung-1G-K4A4G165WF-BCTD.bin
	;;
```

I am not sure where these files are located and those need to be file size checked in order to answer this.

**Comment by eranmati** [comment]
- The missing images should be in the history of this git.
- What about the jig scripts and images in https://github.com/varjig/meta-variscite-imx-jig?

**Comment by ksloat** [comment]
You are right I see they were removed here:
https://github.com/varjig/var_kit_test/commit/af51373f39b0578d73c6b3467e3c4a3be3914062
Perhaps the mx8mm_vareeprom_dram.sh script is not actively used anymore for the 8? I do not know the history here so I am not sure.

I am not sure about meta-variscite-imx-jig scripts either, probably better for @nsdrude and @varigigi to comment on these questions.
